title: BetterCamps
description: Summer Camp Policy Initiative
theme: just-the-docs

url: https://bettercamps.org

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
